name: Cl

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
    user: actions/checkout@v2

    - name: Run one-line script
      run: echo Hellow, world!

    - name: Run multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your projekt.
